/**
 * User settings (spec §9.5) with defaults, validation and persistence.
 *
 * Anything unrecognised in storage is replaced by the default rather than trusted, so an
 * older or hand-edited value can never put the app into an impossible state.
 */

import { readRaw, STORAGE_KEYS, writeValue } from './store';

export type ThemePreference = 'auto' | 'light' | 'dark';
export type CopyFormat = 'markdown' | 'plain';

export interface Settings {
  schemaVersion: 1;
  theme: ThemePreference;
  /** Size two-host VLSM requirements as a /31 rather than a /30 (RFC 3021). */
  allowSlash31: boolean;
  /** Append the `Generated by NetCarve — attv.uk` line to exports. */
  exportFooter: boolean;
  defaultCopyFormat: CopyFormat;
}

export const SETTINGS_SCHEMA_VERSION = 1;

export const DEFAULT_SETTINGS: Settings = {
  schemaVersion: 1,
  theme: 'auto',
  allowSlash31: false,
  exportFooter: true,
  defaultCopyFormat: 'markdown',
};

const THEMES: readonly ThemePreference[] = ['auto', 'light', 'dark'];
const COPY_FORMATS: readonly CopyFormat[] = ['markdown', 'plain'];

function pick<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T {
  return typeof value === 'string' && (allowed as readonly string[]).includes(value)
    ? (value as T)
    : fallback;
}

function boolean(value: unknown, fallback: boolean): boolean {
  return typeof value === 'boolean' ? value : fallback;
}

/** Coerces any stored shape into valid settings. */
export function normaliseSettings(raw: unknown): Settings {
  if (typeof raw !== 'object' || raw === null) return { ...DEFAULT_SETTINGS };
  const value = raw as Record<string, unknown>;
  return {
    schemaVersion: SETTINGS_SCHEMA_VERSION,
    theme: pick(value.theme, THEMES, DEFAULT_SETTINGS.theme),
    allowSlash31: boolean(value.allowSlash31, DEFAULT_SETTINGS.allowSlash31),
    exportFooter: boolean(value.exportFooter, DEFAULT_SETTINGS.exportFooter),
    defaultCopyFormat: pick(
      value.defaultCopyFormat,
      COPY_FORMATS,
      DEFAULT_SETTINGS.defaultCopyFormat,
    ),
  };
}

export async function loadSettings(): Promise<Settings> {
  return normaliseSettings(await readRaw(STORAGE_KEYS.settings));
}

export async function saveSettings(settings: Settings): Promise<boolean> {
  return writeValue(STORAGE_KEYS.settings, normaliseSettings(settings));
}
