/**
 * Markdown export (FR-EXP-01).
 *
 * Every exporter here produces GitHub-flavoured Markdown that pastes cleanly into client
 * documentation, with an optional `Generated by NetCarve — attv.uk` footer that Settings can
 * switch off.
 */

import { strings } from '../../strings';
import type { CalcResult } from '../calc/result';
import type { Project } from '../plan/model';
import { projectSections, PROJECT_COLUMNS } from './project';
import { formatCidr } from '../ip/cidr';
import { groupDigits } from '../format';
import type { VlsmSolution } from '../vlsm/solver';
import type { ConflictReport } from '../conflict/checker';

/** Escapes the only character that can break a Markdown table cell. */
export function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

export function markdownTable(headers: string[], rows: string[][]): string {
  const lines = [
    `| ${headers.map(escapeCell).join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`),
  ];
  return lines.join('\n');
}

export function withFooter(body: string, includeFooter: boolean): string {
  return includeFooter ? `${body}\n\n_${strings.exports.footer}_\n` : `${body}\n`;
}

/** A single calculator result as a two-column Markdown table (FR-CALC-05). */
export function calcToMarkdown(result: CalcResult, includeFooter = true): string {
  const heading = `### ${result.input}`;
  const table = markdownTable(
    ['Field', 'Value'],
    result.fields.map((field) => [field.label, field.value]),
  );

  const sections = [heading, '', table];

  if (result.specials.length > 0) {
    sections.push(
      '',
      `**${strings.calc.specialTitle}**`,
      '',
      ...result.specials.map((match) => {
        const suffix = match.range.deprecated === true ? ` _(${strings.calc.deprecated})_` : '';
        return `- \`${match.range.cidr}\` — ${match.range.label}${suffix}`;
      }),
    );
  }

  if (result.notes.length > 0) {
    sections.push('', ...result.notes.map((note) => `> ${note.text}`));
  }

  return withFooter(sections.join('\n'), includeFooter);
}

/**
 * A whole project as Markdown (FR-EXP-01): the project name as a heading, then one table per
 * root block with the columns `Subnet | Mask | Range | Usable | Name | VLAN | Notes`.
 */
export function projectToMarkdown(project: Project, includeFooter = true): string {
  const lines: string[] = [`## ${project.name}`];
  if (project.client !== undefined) lines.push('', `**Client:** ${project.client}`);
  if (project.notes !== undefined) lines.push('', project.notes);

  const sections = projectSections(project);
  if (sections.length === 0) {
    lines.push('', '_No blocks planned yet._');
  }

  for (const section of sections) {
    lines.push(
      '',
      `### ${section.rootCidr}`,
      '',
      markdownTable([...PROJECT_COLUMNS], section.rows.map((row) => row.cells)),
    );
  }

  return withFooter(lines.join('\n'), includeFooter);
}

const VLSM_COLUMNS = ['Name', 'Allocated block', 'Mask', 'Range', 'Usable', 'Waste'] as const;

/** A solved VLSM allocation as Markdown (FR-VLSM-07). */
export function vlsmToMarkdown(solution: VlsmSolution, includeFooter = true): string {
  const lines: string[] = [
    `## ${strings.vlsm.title} — ${formatCidr(solution.base)}`,
    '',
    markdownTable(
      [...VLSM_COLUMNS],
      solution.allocations.map((entry) => [
        entry.name,
        entry.summary.cidr,
        entry.summary.mask,
        entry.summary.range,
        entry.summary.usable.primary,
        entry.waste.toString(),
      ]),
    ),
    '',
    strings.vlsm.summary(
      groupDigits(solution.allocatedAddresses),
      groupDigits(solution.totalAddresses),
      solution.utilisation,
    ),
  ];

  if (solution.failure !== undefined) {
    lines.push(
      '',
      `> ${strings.vlsm.shortfall(
        solution.failure.name,
        groupDigits(solution.failure.shortfall),
      )}`,
    );
  }

  lines.push(
    '',
    `**${strings.vlsm.freeBlocks}**`,
    '',
    solution.free.length === 0
      ? `_${strings.vlsm.noFreeBlocks}_`
      : solution.free.map((block) => `- \`${formatCidr(block)}\``).join('\n'),
  );

  return withFooter(lines.join('\n'), includeFooter);
}

/** A conflict report as Markdown (FR-CONF-06). */
export function conflictsToMarkdown(report: ConflictReport, includeFooter = true): string {
  const lines: string[] = [`## ${strings.conflicts.title}`, ''];

  if (report.clean) {
    lines.push(strings.conflicts.clean(report.blockCount));
  } else {
    if (report.identical.length > 0) {
      lines.push(`### ${strings.conflicts.identical}`, '');
      for (const group of report.identical) {
        lines.push(`- \`${group.cidr}\` — lines ${group.lines.join(', ')}`);
      }
      lines.push('');
    }
    if (report.containment.length > 0) {
      lines.push(`### ${strings.conflicts.containment}`, '');
      for (const chain of report.containment) {
        lines.push(`- ${chain.blocks.map((block) => `\`${block.cidr}\``).join(' ⊃ ')}`);
      }
      lines.push('');
    }
    lines.push(`> ${strings.conflicts.alignmentNote}`);
  }

  if (report.errors.length > 0) {
    lines.push('', `### ${strings.conflicts.invalidLines(report.errors.length)}`, '');
    for (const error of report.errors) {
      lines.push(`- ${strings.conflicts.lineError(error.line, error.text, error.message)}`);
    }
  }

  return withFooter(lines.join('\n'), includeFooter);
}
