/**
 * Markdown export (FR-EXP-01).
 *
 * Every exporter here produces GitHub-flavoured Markdown that pastes cleanly into client
 * documentation, with an optional `Generated by NetCarve — attv.uk` footer that Settings can
 * switch off.
 */

import { strings } from '../../strings';
import type { CalcResult } from '../calc/result';
import type { Project } from '../plan/model';
import { projectSections, PROJECT_COLUMNS } from './project';

/** Escapes the only character that can break a Markdown table cell. */
export function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

export function markdownTable(headers: string[], rows: string[][]): string {
  const lines = [
    `| ${headers.map(escapeCell).join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`),
  ];
  return lines.join('\n');
}

export function withFooter(body: string, includeFooter: boolean): string {
  return includeFooter ? `${body}\n\n_${strings.exports.footer}_\n` : `${body}\n`;
}

/** A single calculator result as a two-column Markdown table (FR-CALC-05). */
export function calcToMarkdown(result: CalcResult, includeFooter = true): string {
  const heading = `### ${result.input}`;
  const table = markdownTable(
    ['Field', 'Value'],
    result.fields.map((field) => [field.label, field.value]),
  );

  const sections = [heading, '', table];

  if (result.specials.length > 0) {
    sections.push(
      '',
      `**${strings.calc.specialTitle}**`,
      '',
      ...result.specials.map((match) => {
        const suffix = match.range.deprecated === true ? ` _(${strings.calc.deprecated})_` : '';
        return `- \`${match.range.cidr}\` — ${match.range.label}${suffix}`;
      }),
    );
  }

  if (result.notes.length > 0) {
    sections.push('', ...result.notes.map((note) => `> ${note.text}`));
  }

  return withFooter(sections.join('\n'), includeFooter);
}

/**
 * A whole project as Markdown (FR-EXP-01): the project name as a heading, then one table per
 * root block with the columns `Subnet | Mask | Range | Usable | Name | VLAN | Notes`.
 */
export function projectToMarkdown(project: Project, includeFooter = true): string {
  const lines: string[] = [`## ${project.name}`];
  if (project.client !== undefined) lines.push('', `**Client:** ${project.client}`);
  if (project.notes !== undefined) lines.push('', project.notes);

  const sections = projectSections(project);
  if (sections.length === 0) {
    lines.push('', '_No blocks planned yet._');
  }

  for (const section of sections) {
    lines.push(
      '',
      `### ${section.rootCidr}`,
      '',
      markdownTable([...PROJECT_COLUMNS], section.rows.map((row) => row.cells)),
    );
  }

  return withFooter(lines.join('\n'), includeFooter);
}
