import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test, expect, goToRoute, readClipboard, resetStorage } from './fixtures';
import type { Page } from '@playwright/test';

async function seedProject(page: Page): Promise<void> {
  await goToRoute(page, '/projects');
  await page.getByLabel('Project name').fill('Acme HQ');
  await page.getByLabel('Client (optional)').fill('Acme Ltd');
  await page.getByRole('button', { name: 'New project' }).click();
  await page.getByLabel('Add a root block').fill('10.20.0.0/16');
  await page.getByRole('button', { name: 'Add block' }).click();
  await page.locator('.nc-tree__item').first().getByRole('button', { name: 'Split', exact: true }).click();
  await page.locator('.nc-tree__item').nth(1).getByRole('button', { name: 'Edit' }).click();
  await page.locator('.nc-editor').getByLabel('Name').fill('Office');
  await page.locator('.nc-editor').getByLabel('VLAN ID').fill('10');
  await page.locator('.nc-editor').getByRole('button', { name: 'Done' }).click();
}

/** Saves a download to disk and hands back its text. */
async function downloadText(page: Page, name: string | RegExp): Promise<string> {
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name }).click();
  const download = await pending;
  const dir = await mkdtemp(join(tmpdir(), 'netcarve-dl-'));
  const path = join(dir, download.suggestedFilename());
  await download.saveAs(path);
  return readFile(path, 'utf8');
}

test.describe('exports and imports (F8)', () => {
  test.beforeEach(async ({ app }) => {
    await resetStorage(app);
    await seedProject(app);
  });

  test('copies a plan as Markdown', async ({ app }) => {
    await app.getByRole('button', { name: 'Copy as Markdown' }).click();
    const copied = await readClipboard(app);
    expect(copied).toContain('# Acme HQ');
    expect(copied).toContain('10.20.0.0/17');
    expect(copied).toContain('Office');
    expect(copied).toContain('Generated by NetCarve');
  });

  test('downloads the plan as CSV with a header row', async ({ app }) => {
    const csv = await downloadText(app, 'Download CSV');
    const [header] = csv.trim().split('\n');
    expect(header).toContain('Subnet,Mask,Range,Usable,Name,VLAN,Notes');
    expect(csv).toContain('10.20.0.0/17');
    expect(csv).toContain('Office');
  });

  test('downloads the plan as JSON that round-trips', async ({ app }) => {
    const json = await downloadText(app, 'Download JSON');
    const parsed = JSON.parse(json) as Record<string, any>;
    expect(parsed.app).toBe('netcarve');
    expect(parsed.schemaVersion).toBe(1);
    expect(parsed.project.name).toBe('Acme HQ');
    expect(parsed.project.roots[0].children[0].name).toBe('Office');
    expect(parsed.project.roots[0].children[0].vlanId).toBe(10);
  });

  test('re-imports an export as a project (FR-EXP-03)', async ({ app }) => {
    const json = await downloadText(app, 'Download JSON');
    const dir = await mkdtemp(join(tmpdir(), 'netcarve-up-'));
    const path = join(dir, 'netcarve-export.json');
    // A fresh id and name, so the import lands as a second project rather than an in-place
    // update of the one it came from.
    const envelope = JSON.parse(json) as Record<string, any>;
    envelope.project.id = '11111111-2222-3333-4444-555555555555';
    envelope.project.name = 'Acme HQ (restored)';
    await writeFile(path, JSON.stringify(envelope), 'utf8');

    await goToRoute(app, '/projects');
    await app.getByLabel('Choose a NetCarve JSON file').setInputFiles(path);

    await expect(app.locator('.nc-toast')).toContainText('Imported “Acme HQ (restored)”.');
    await expect(app.locator('.nc-card')).toHaveCount(2);
  });

  test('refuses a file that is not a NetCarve export', async ({ app }) => {
    const dir = await mkdtemp(join(tmpdir(), 'netcarve-bad-'));
    const path = join(dir, 'not-netcarve.json');
    await writeFile(path, JSON.stringify({ hello: 'world' }), 'utf8');

    await goToRoute(app, '/projects');
    await app.getByLabel('Choose a NetCarve JSON file').setInputFiles(path);

    await expect(app.locator('.nc-toast--error')).toContainText('That file is not a NetCarve export.');
    await expect(app.locator('.nc-card')).toHaveCount(1);
  });

  test('refuses an export from a schema version it cannot read', async ({ app }) => {
    const json = await downloadText(app, 'Download JSON');
    const bumped = JSON.parse(json) as Record<string, any>;
    bumped.schemaVersion = 99;
    const dir = await mkdtemp(join(tmpdir(), 'netcarve-ver-'));
    const path = join(dir, 'future.json');
    await writeFile(path, JSON.stringify(bumped), 'utf8');

    await goToRoute(app, '/projects');
    await app.getByLabel('Choose a NetCarve JSON file').setInputFiles(path);
    await expect(app.locator('.nc-toast--error')).toContainText('schema version 99');
  });

  test('exports every project from the Projects view', async ({ app }) => {
    await goToRoute(app, '/projects');
    const json = await downloadText(app, 'Export all projects');
    const envelope = JSON.parse(json) as Record<string, any>;
    expect(envelope.projects).toHaveLength(1);
    expect(envelope.projects[0].name).toBe('Acme HQ');
  });
});
