import { test, expect, goToRoute, readStorage, resetStorage } from './fixtures';

test.describe('settings and stored data (F7)', () => {
  test.beforeEach(async ({ app }) => {
    await resetStorage(app);
    await goToRoute(app, '/settings');
  });

  test('switches theme and remembers the choice', async ({ app }) => {
    await app.getByRole('radio', { name: 'Dark' }).check();
    await expect(app.locator('html')).toHaveAttribute('data-theme', 'dark');

    await app.reload();
    await goToRoute(app, '/settings');
    await expect(app.getByRole('radio', { name: 'Dark' })).toBeChecked();
    await expect(app.locator('html')).toHaveAttribute('data-theme', 'dark');

    await app.getByRole('radio', { name: 'Light' }).check();
    await expect(app.locator('html')).toHaveAttribute('data-theme', 'light');
  });

  test('persists the toggles and the copy format', async ({ app }) => {
    await app.getByLabel('Allow /31 for two-host links').check();
    await app.getByLabel('Add a NetCarve credit line to exports').uncheck();
    await app.getByLabel('Default copy format').selectOption('plain');

    await expect
      .poll(async () => await readStorage(app, 'netcarve:settings'))
      .toMatchObject({ allowSlash31: true, exportFooter: false, defaultCopyFormat: 'plain' });

    await app.reload();
    await goToRoute(app, '/settings');
    await expect(app.getByLabel('Allow /31 for two-host links')).toBeChecked();
    await expect(app.getByLabel('Add a NetCarve credit line to exports')).not.toBeChecked();
  });

  test('drops the credit line from exports when the toggle is off', async ({ app }) => {
    await app.getByLabel('Add a NetCarve credit line to exports').uncheck();
    await goToRoute(app, '/calc');
    await app.getByLabel('IP address or CIDR block').fill('10.20.0.0/16');
    await app.getByRole('button', { name: 'Copy as Markdown' }).click();
    const copied = await app.evaluate(() => navigator.clipboard.readText());
    expect(copied).not.toContain('Generated by NetCarve');
  });

  test('states the planner limit and the privacy position', async ({ app }) => {
    await expect(app.locator('.nc-panel').first()).toContainText(
      'A single root block can hold up to',
    );
    await expect(app.locator('.nc-panel').nth(1)).toContainText(
      'There is no account, no server and no network request.',
    );
  });

  test('exports every project as one JSON file', async ({ app }) => {
    const download = app.waitForEvent('download');
    await app.getByRole('button', { name: 'Export all data' }).click();
    const file = await download;
    expect(file.suggestedFilename()).toBe('netcarve-projects.json');
  });

  test('only deletes everything once DELETE is typed', async ({ app }) => {
    await goToRoute(app, '/projects');
    await app.getByLabel('Project name').fill('Doomed');
    await app.getByRole('button', { name: 'New project' }).click();
    await goToRoute(app, '/settings');

    const button = app.getByRole('button', { name: 'Delete all data' });
    await expect(button).toBeDisabled();

    await app.getByLabel('Type DELETE to remove every project and setting').fill('delete');
    await expect(button).toBeDisabled();

    await app.getByLabel('Type DELETE to remove every project and setting').fill('DELETE');
    await expect(button).toBeEnabled();
    await button.click();

    await expect(app.locator('.nc-hint--success')).toHaveText('Everything has been removed.');
    await expect.poll(async () => await readStorage(app, 'netcarve:projects')).toBeUndefined();

    await goToRoute(app, '/projects');
    await expect(app.locator('.nc-empty')).toContainText('No projects yet');
  });
});
