import { describe, expect, it } from 'vitest';
import { csvField, projectToCsv, toCsv } from '@/src/lib/export/csv';
import {
  EXPORT_APP,
  parseProjectJson,
  projectsToJson,
  projectToJson,
} from '@/src/lib/export/json';
import { projectToMarkdown } from '@/src/lib/export/markdown';
import { PROJECT_COLUMNS, projectSections } from '@/src/lib/export/project';
import { slugify } from '@/src/lib/export/download';
import { createProject, type PlanNode, type Project } from '@/src/lib/plan/model';
import { splitToPrefix, updateNode } from '@/src/lib/plan/tree';

function plannedProject(): Project {
  let root: PlanNode = { cidr: '10.20.0.0/16' };
  const carved = splitToPrefix(root, [], 18);
  if (!carved.ok) throw new Error('carve failed');
  root = carved.value;

  const named = updateNode(root, [0, 0], {
    name: 'VLAN 10 — Office',
    vlanId: 10,
    colour: 'blue',
    notes: 'Desks, printers | phones',
  });
  if (!named.ok) throw new Error('naming failed');

  return {
    ...createProject('Acme refresh', { client: 'Acme Ltd', notes: 'Head office', now: 1000 }),
    id: 'acme-1',
    roots: [named.value],
  };
}

describe('projectSections', () => {
  it('produces the specified columns, in address order', () => {
    const [section] = projectSections(plannedProject());
    expect(PROJECT_COLUMNS).toEqual([
      'Subnet',
      'Mask',
      'Range',
      'Usable',
      'Name',
      'VLAN',
      'Notes',
    ]);
    expect(section?.rootCidr).toBe('10.20.0.0/16');
    expect(section?.rows).toHaveLength(4);
    expect(section?.rows[0]?.cells).toEqual([
      '10.20.0.0/18',
      '255.255.192.0',
      '10.20.0.0 – 10.20.63.255',
      '16,382',
      'VLAN 10 — Office',
      '10',
      'Desks, printers | phones',
    ]);
    expect(section?.rows[1]?.cells[4]).toBe('');
  });

  it('leaves the mask blank for IPv6 rows', () => {
    const project = { ...createProject('v6'), roots: [{ cidr: '2001:db8::/64' }] };
    const [section] = projectSections(project);
    expect(section?.rows[0]?.cells[1]).toBe('');
    expect(section?.rows[0]?.cells[0]).toBe('2001:db8::/64');
  });

  it('can emit plain digits for the usable count', () => {
    const [section] = projectSections(plannedProject(), true);
    expect(section?.rows[0]?.cells[3]).toBe('16382');
  });
});

describe('Markdown export (FR-EXP-01)', () => {
  const markdown = projectToMarkdown(plannedProject());

  it('carries the project name, client and root heading', () => {
    expect(markdown).toContain('## Acme refresh');
    expect(markdown).toContain('**Client:** Acme Ltd');
    expect(markdown).toContain('### 10.20.0.0/16');
  });

  it('uses the specified columns', () => {
    expect(markdown).toContain('| Subnet | Mask | Range | Usable | Name | VLAN | Notes |');
  });

  it('escapes a pipe inside a cell', () => {
    expect(markdown).toContain('Desks, printers \\| phones');
  });

  it('carries the credit footer, and can leave it out', () => {
    expect(markdown).toContain('_Generated by NetCarve — attv.uk_');
    expect(projectToMarkdown(plannedProject(), false)).not.toContain('attv.uk');
  });

  it('says so when nothing is planned yet', () => {
    expect(projectToMarkdown(createProject('Empty'))).toContain('_No blocks planned yet._');
  });
});

describe('CSV export (FR-EXP-02)', () => {
  it('quotes only what RFC 4180 requires', () => {
    expect(csvField('plain')).toBe('plain');
    expect(csvField('has,comma')).toBe('"has,comma"');
    expect(csvField('has"quote')).toBe('"has""quote"');
    expect(csvField('has\nnewline')).toBe('"has\nnewline"');
    expect(csvField('has\r\nbreak')).toBe('"has\r\nbreak"');
  });

  it('uses CRLF line endings and a trailing break', () => {
    expect(toCsv(['a', 'b'], [['1', '2']])).toBe('a,b\r\n1,2\r\n');
  });

  it('exports the project rows', () => {
    const csv = projectToCsv(plannedProject());
    expect(csv.split('\r\n')[0]).toBe('Subnet,Mask,Range,Usable,Name,VLAN,Notes');
    expect(csv).toContain('10.20.0.0/18,255.255.192.0,');
    expect(csv).toContain('"Desks, printers | phones"');
  });

  it('adds a Root column when the project has more than one root', () => {
    const project = {
      ...createProject('Two roots'),
      roots: [{ cidr: '10.0.0.0/8' }, { cidr: '172.16.0.0/12' }],
    };
    const csv = projectToCsv(project);
    expect(csv.split('\r\n')[0]).toBe('Root,Subnet,Mask,Range,Usable,Name,VLAN,Notes');
    expect(csv).toContain('10.0.0.0/8,10.0.0.0/8,');
  });
});

describe('JSON export and import (FR-EXP-03)', () => {
  it('writes the documented envelope', () => {
    const parsed = JSON.parse(projectToJson(plannedProject())) as Record<string, unknown>;
    expect(parsed.app).toBe(EXPORT_APP);
    expect(parsed.schemaVersion).toBe(1);
    expect((parsed.project as Project).name).toBe('Acme refresh');
  });

  it('round-trips a project', () => {
    const original = plannedProject();
    const result = parseProjectJson(projectToJson(original));
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.projects).toHaveLength(1);
      expect(result.projects[0]?.roots).toEqual(original.roots);
      expect(result.quarantined).toEqual([]);
    }
  });

  it('round-trips every project from an export-all', () => {
    const all = projectsToJson([plannedProject(), createProject('Second')]);
    const result = parseProjectJson(all);
    expect(result.ok).toBe(true);
    if (result.ok) expect(result.projects.map((project) => project.name)).toEqual([
      'Acme refresh',
      'Second',
    ]);
  });

  it.each([
    ['not JSON at all', 'nonsense{'],
    ['a JSON scalar', '42'],
    ['a foreign export', JSON.stringify({ app: 'something-else', schemaVersion: 1 })],
    ['an envelope with no projects', JSON.stringify({ app: 'netcarve', schemaVersion: 1 })],
    [
      'an envelope whose project is unusable',
      JSON.stringify({ app: 'netcarve', schemaVersion: 1, project: { nope: true } }),
    ],
  ])('refuses %s', (_label, text) => {
    const result = parseProjectJson(text);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.message).toBe('That file is not a NetCarve export.');
  });

  it('refuses a schema version it cannot read', () => {
    const result = parseProjectJson(
      JSON.stringify({ app: 'netcarve', schemaVersion: 7, project: plannedProject() }),
    );
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.message).toMatch(/schema version 7/);
  });

  it('quarantines a broken root inside an otherwise valid import', () => {
    const project = {
      ...createProject('Acme'),
      roots: [{ cidr: '10.0.0.0/8', children: [{ cidr: '10.0.0.0/9' }, { cidr: '11.0.0.0/9' }] }],
    };
    const result = parseProjectJson(
      JSON.stringify({ app: 'netcarve', schemaVersion: 1, project }),
    );
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.projects[0]?.roots).toEqual([]);
      expect(result.quarantined).toHaveLength(1);
    }
  });
});

describe('slugify', () => {
  it.each([
    ['Acme refresh', 'acme-refresh'],
    ['  Head Office / 2026  ', 'head-office-2026'],
    ['!!!', 'netcarve'],
  ])('%s becomes %s', (input, expected) => {
    expect(slugify(input)).toBe(expected);
  });
});
