import { describe, expect, it } from 'vitest';
import { buildCalcResult } from '@/src/lib/calc/result';
import { checkConflicts } from '@/src/lib/conflict/checker';
import {
  calcToPlain,
  conflictsToPlain,
  plainTable,
  projectToPlain,
  vlsmToPlain,
} from '@/src/lib/export/plain';
import { createProject, nodeFromCidr } from '@/src/lib/plan/model';
import { parseCidr } from '@/src/lib/ip/cidr';
import { solveVlsm, type VlsmSolution } from '@/src/lib/vlsm/solver';
import { splitNode, updateNode } from '@/src/lib/plan/tree';

function result(input: string) {
  const outcome = buildCalcResult(input);
  if (!outcome.ok) throw new Error(outcome.message);
  return outcome.result;
}

function solve(base: string, requirements: Array<[string, number]>): VlsmSolution {
  const outcome = solveVlsm(
    base,
    requirements.map(([name, requiredHosts]) => ({ name, requiredHosts })),
  );
  if (!outcome.ok) throw new Error(outcome.message);
  return outcome.solution;
}

/** A two-leaf plan: 10.20.0.0/16 split once, with the left half named. */
function plan() {
  const parsed = parseCidr('10.20.0.0/16');
  if (!parsed.ok) throw new Error('unreachable');
  const split = splitNode(nodeFromCidr(parsed.value), []);
  if (!split.ok) throw new Error('unreachable');
  const named = updateNode(split.value, [0], { name: 'Office', vlanId: 10 });
  if (!named.ok) throw new Error('unreachable');
  return { ...createProject('Acme HQ', { client: 'Acme Ltd' }), roots: [named.value] };
}

describe('plainTable', () => {
  it('pads every column to its widest cell', () => {
    const table = plainTable(['Name', 'Block'], [['Office', '10.0.0.0/24'], ['A', '10.0.1.0/24']]);
    const [header, rule, first, second] = table.split('\n');

    expect(header).toBe('Name    Block');
    expect(rule).toBe('------  -----------');
    expect(first).toBe('Office  10.0.0.0/24');
    expect(second).toBe('A       10.0.1.0/24');
  });

  it('never leaves trailing spaces on a short last cell', () => {
    const table = plainTable(['A', 'B'], [['long value', '']]);
    for (const line of table.split('\n')) expect(line).toBe(line.trimEnd());
  });

  it('pads a ragged row out to the full width', () => {
    const table = plainTable(['A', 'B'], [['x'], ['yy', 'zz']]);
    expect(table.split('\n')[2]).toBe('x');
    expect(table.split('\n')[3]).toBe('yy  zz');
  });

  it('ignores a cell with no column to sit in', () => {
    expect(plainTable(['A'], [['x', 'extra']])).toContain('x  extra');
  });

  it('carries no Markdown syntax at all', () => {
    const table = plainTable(['A'], [['x']]);
    expect(table).not.toContain('|');
  });
});

describe('calcToPlain', () => {
  it('lists every field the Markdown export lists, without the pipes', () => {
    const text = calcToPlain(result('10.20.0.0/16'));

    expect(text).toContain('10.20.0.0/16');
    expect(text).toContain('Subnet mask');
    expect(text).toContain('255.255.0.0');
    expect(text).toContain('Reserved ranges:');
    expect(text).toContain('10.0.0.0/8');
    expect(text).toContain('Generated by NetCarve — attv.uk');
    expect(text).not.toContain('|');
    expect(text).not.toContain('###');
  });

  it('carries the IPv6 notes and drops the footer when asked', () => {
    const text = calcToPlain(result('2001:db8::/48'), false);
    expect(text).toContain('IPv6 has no broadcast address');
    expect(text).not.toContain('Generated by NetCarve');
  });

  it('omits the reserved-ranges block when there is none to report', () => {
    const text = calcToPlain(result('8.8.8.0/24'));
    expect(text).not.toContain('Reserved ranges:');
    expect(text).toContain('8.8.8.0');
  });

  it('marks a deprecated reserved range', () => {
    expect(calcToPlain(result('192.88.99.0/24'))).toContain('(deprecated)');
  });
});

describe('projectToPlain', () => {
  it('renders the client, the root and the named leaf', () => {
    const text = projectToPlain(plan());

    expect(text).toContain('Acme HQ');
    expect(text).toContain('Client: Acme Ltd');
    expect(text).toContain('10.20.0.0/16');
    expect(text).toContain('Subnet');
    expect(text).toContain('Office');
    expect(text).not.toContain('|');
  });

  it('carries the project notes when there are any', () => {
    const project = { ...plan(), notes: 'Cutover on the 14th.' };
    expect(projectToPlain(project)).toContain('Cutover on the 14th.');
  });

  it('says so when there is nothing planned yet', () => {
    expect(projectToPlain(createProject('Empty', {}), false)).toContain('No blocks planned yet.');
  });
});

describe('vlsmToPlain', () => {
  it('renders the allocation, the summary and the free blocks', () => {
    const text = vlsmToPlain(
      solve('192.168.10.0/24', [
        ['Warehouse', 120],
        ['Office', 50],
      ]),
    );

    expect(text).toContain('VLSM solver — 192.168.10.0/24');
    expect(text).toContain('Warehouse');
    expect(text).toContain('192.168.10.0/25');
    expect(text).toContain('192 of 256 addresses allocated — 75% utilisation.');
    expect(text).toContain('Free blocks:');
    expect(text).toContain('192.168.10.192/26');
    expect(text).not.toContain('|');
  });

  it('reports a shortfall and an exhausted base network', () => {
    const text = vlsmToPlain(
      solve('10.0.0.0/25', [
        ['A', 126],
        ['B', 10],
      ]),
      false,
    );
    expect(text).toContain('B does not fit. The base network is 16 addresses short.');
    expect(text).toContain('Every address in the base network is allocated.');
  });
});

describe('conflictsToPlain', () => {
  it('reports duplicates, containment and bad lines', () => {
    const text = conflictsToPlain(
      checkConflicts('10.0.0.0/8\n10.1.0.0/16\n10.0.0.0/8\n300.0.0.0/8'),
    );

    expect(text).toContain('Identical blocks:');
    expect(text).toContain('10.0.0.0/8 — lines 1, 3');
    expect(text).toContain('Containment:');
    expect(text).toContain('10.0.0.0/8 ⊃ 10.1.0.0/16');
    expect(text).toContain('Line 4');
    expect(text).not.toContain('`');
  });

  it('reports containment on its own, with no duplicates to list', () => {
    const text = conflictsToPlain(checkConflicts('10.0.0.0/8\n10.1.0.0/16'), false);
    expect(text).not.toContain('Identical blocks:');
    expect(text).toContain('Containment:');
  });

  it('reports duplicates on its own, with nothing containing anything', () => {
    const text = conflictsToPlain(checkConflicts('10.0.0.0/8\n10.0.0.0/8'), false);
    expect(text).toContain('Identical blocks:');
    expect(text).not.toContain('Containment:');
  });

  it('names bad lines even when the rest of the list is clean', () => {
    const text = conflictsToPlain(checkConflicts('10.0.0.0/24\nnonsense'), false);
    expect(text).toContain('No overlaps found across 1 block.');
    expect(text).toContain('Line 2');
  });

  it('reports a clean list', () => {
    expect(conflictsToPlain(checkConflicts('10.0.0.0/24\n10.0.1.0/24'), false)).toContain(
      'No overlaps found across 2 blocks.',
    );
  });
});
