import { describe, expect, it } from 'vitest';
import { vlsmToCsv } from '@/src/lib/export/csv';
import { conflictsToMarkdown, vlsmToMarkdown } from '@/src/lib/export/markdown';
import { checkConflicts } from '@/src/lib/conflict/checker';
import { solveVlsm, type VlsmSolution } from '@/src/lib/vlsm/solver';

function solve(base: string, requirements: Array<[string, number]>): VlsmSolution {
  const result = solveVlsm(
    base,
    requirements.map(([name, requiredHosts]) => ({ name, requiredHosts })),
  );
  if (!result.ok) throw new Error(result.message);
  return result.solution;
}

describe('vlsmToMarkdown (FR-VLSM-07)', () => {
  it('renders the allocation, summary and free blocks', () => {
    const markdown = vlsmToMarkdown(
      solve('192.168.10.0/24', [
        ['Warehouse', 120],
        ['Office', 50],
      ]),
    );
    expect(markdown).toContain('## VLSM solver — 192.168.10.0/24');
    expect(markdown).toContain('| Name | Allocated block | Mask | Range | Usable | Waste |');
    expect(markdown).toContain('| Warehouse | 192.168.10.0/25 | 255.255.255.128 |');
    expect(markdown).toContain('192 of 256 addresses allocated — 75% utilisation.');
    expect(markdown).toContain('- `192.168.10.192/26`');
    expect(markdown).toContain('_Generated by NetCarve — attv.uk_');
  });

  it('notes a shortfall and an exhausted base network', () => {
    const markdown = vlsmToMarkdown(
      solve('10.0.0.0/25', [
        ['A', 126],
        ['B', 10],
      ]),
      false,
    );
    expect(markdown).toContain('> B does not fit. The base network is 16 addresses short.');
    expect(markdown).toContain('_Every address in the base network is allocated._');
    expect(markdown).not.toContain('attv.uk');
  });
});

describe('vlsmToCsv (FR-VLSM-07)', () => {
  it('writes the same columns with plain-digit counts', () => {
    const csv = vlsmToCsv(solve('192.168.10.0/24', [['Warehouse', 120]]));
    expect(csv.split('\r\n')[0]).toBe('Name,Allocated block,Mask,Range,Usable,Waste');
    expect(csv).toContain('Warehouse,192.168.10.0/25,255.255.255.128,');
    expect(csv).toContain(',126,6\r\n');
  });
});

describe('conflictsToMarkdown (FR-CONF-06)', () => {
  it('reports a clean list', () => {
    const markdown = conflictsToMarkdown(checkConflicts('10.0.0.0/8\n172.16.0.0/12'));
    expect(markdown).toContain('No overlaps found across 2 blocks.');
    expect(markdown).not.toContain('### Containment');
  });

  it('reports duplicates, chains, the alignment note and skipped lines', () => {
    const markdown = conflictsToMarkdown(
      checkConflicts('10.0.0.0/8\n10.0.0.0/8\n10.1.0.0/16\n999.1.1.1'),
      false,
    );
    expect(markdown).toContain('### Identical blocks');
    expect(markdown).toContain('`10.0.0.0/8` — lines 1, 2');
    expect(markdown).toContain('### Containment');
    expect(markdown).toContain('`10.0.0.0/8` ⊃ `10.1.0.0/16`');
    expect(markdown).toContain('aligned to their own size');
    expect(markdown).toContain('### 1 line was skipped.');
    expect(markdown).toContain('Line 4 — “999.1.1.1”');
  });
});
