import { fireEvent, render, screen, waitFor } from '@testing-library/preact';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from '@/entrypoints/app/App';
import { setStorageArea } from '@/src/lib/storage/store';

beforeEach(() => {
  setStorageArea({
    async get() {
      return undefined;
    },
    async set() {
      /* no-op */
    },
    async remove() {
      /* no-op */
    },
  });
  globalThis.location.hash = '#/conflicts';
  Object.assign(navigator, { clipboard: { writeText: vi.fn().mockResolvedValue(undefined) } });
});

afterEach(() => {
  setStorageArea(undefined);
  vi.restoreAllMocks();
});

const paste = (text: string) => {
  fireEvent.input(screen.getByLabelText('Blocks, one per line'), { target: { value: text } });
};

describe('Conflict checker (F5)', () => {
  it('starts empty', () => {
    render(<App version="1.0.0" />);
    expect(screen.getByText('Nothing to check yet.')).toBeInTheDocument();
  });

  it('reports a clean list (FR-CONF-04)', async () => {
    render(<App version="1.0.0" />);
    paste('10.0.0.0/8\n172.16.0.0/12\n192.168.0.0/16');

    expect(await screen.findByRole('status')).toHaveTextContent(
      'No overlaps found across 3 blocks.',
    );
  });

  it('reports identical entries with their line numbers', async () => {
    render(<App version="1.0.0" />);
    paste('10.0.0.0/8\n# a comment\n10.0.0.0/8');

    expect(await screen.findByText('Identical blocks')).toBeInTheDocument();
    expect(screen.getByText(/lines 1, 3/)).toBeInTheDocument();
  });

  it('reports a containment chain (FR-CONF-03)', async () => {
    render(<App version="1.0.0" />);
    paste('10.0.0.0/8\n10.1.0.0/16\n10.1.2.0/24');

    expect(await screen.findByText('Containment')).toBeInTheDocument();
    const chain = screen.getByText('10.1.2.0/24').closest('li');
    expect(chain?.textContent).toContain('10.0.0.0/8');
    expect(chain?.textContent).toContain('⊃');
    expect(
      screen.getByText(/aligned to their own size/),
    ).toBeInTheDocument();
  });

  it('reports unreadable lines without dropping the rest (FR-CONF-01)', async () => {
    render(<App version="1.0.0" />);
    paste('10.0.0.0/8\n999.1.1.1\n172.16.0.0/12');

    expect(await screen.findByText('1 line was skipped.')).toBeInTheDocument();
    expect(screen.getByText(/Line 2 — “999\.1\.1\.1”/)).toBeInTheDocument();
    expect(screen.getByRole('status')).toHaveTextContent('No overlaps found across 2 blocks.');
  });

  it('never conflicts across families (FR-CONF-02)', async () => {
    render(<App version="1.0.0" />);
    paste('0.0.0.0/0\n::/0');
    expect(await screen.findByRole('status')).toHaveTextContent('No overlaps found across 2 blocks');
  });

  it('exports the report as Markdown (FR-CONF-06)', async () => {
    render(<App version="1.0.0" />);
    paste('10.0.0.0/8\n10.1.0.0/16');
    await screen.findByText('Containment');

    fireEvent.click(screen.getByRole('button', { name: 'Copy as Markdown' }));
    await waitFor(() => expect(navigator.clipboard.writeText).toHaveBeenCalled());

    const [markdown] = vi.mocked(navigator.clipboard.writeText).mock.calls[0] as [string];
    expect(markdown).toContain('### Containment');
    expect(markdown).toContain('`10.0.0.0/8` ⊃ `10.1.0.0/16`');
    expect(markdown).toContain('_Generated by NetCarve — attv.uk_');
  });
});
